#cloud-config
package_update: true
packages:
  - docker.io
write_files:  
  - path: /root/index.html
    content: |
      coreeeeeee

runcmd:
  - cd /root/.ssh  
  - sudo apt-get -y update  
  - sudo apt-get -y install docker  
  - sudo service docker start     
  - docker run -d -v /root/index.html:/usr/share/nginx/html/index.html -p 80:80 nginx